version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tdreader"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4sq6mlspgsya"
s3_prefix = "tdreader"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

